name: WaffleHouseIndex
description: A Flutter app to display the Waffle House Index near the user's current location (within 50 miles or more).
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  geolocator: ^14.0.2
  geolocator_linux: ^0.2.1
  intl: ^0.20.2
  collection: ^1.18.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.2.3
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
