name: whi_flutter
description: A Flutter app to display the Waffle House Index near the user's current location (within 50 miles).
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  geolocator: ^11.0.0
  geolocator_linux: ^0.2.1
  intl: ^0.19.0
  collection: ^1.18.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_local_notifications: ^17.1.0
  shared_preferences: ^2.2.3
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
